In [21]:
# Import du fichier train
import pandas as pd
df_sales = pd.read_csv(
     r"C:\Users\diawn\Downloads\Recherche_emploi\Projet_analyse_vente\train.csv"
)
df_sales.head(5)

# Controle qualité des données
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   object
 18  Unnamed: 18    6 non-null      float64
dtypes: float64(2), int64(1), object(16)
memory usage: 1.4+ MB

In [ ]:
# Nettoyage des données

# Conversion des champs date en datetime
df_sales["Order Date"] = pd.to_datetime(df_sales["Order Date"], dayfirst=True)
df_sales["Ship Date"] = pd.to_datetime(df_sales["Ship Date"], dayfirst=True)
df_sales.info()

# Recherche de doublons 
df_sales.duplicated().sum() # le résultat est 0, il y'a aucun doublon dans le dataframe

# Recherche de valeurs manquantes
df_sales.isna().sum() # il y'a 11 valeurs manquantes dans la colonne postal code et une colonne créée lors de l'import unnamed

# Suppression de la colonne créée unnamed qui ne sert pas dans les données
df_sales.drop(columns = "Unnamed: 18", inplace = True)

df_sales.head()

# On laissera les valeurs manquantes de postal code comme tel

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   datetime64[ns]
 3   Ship Date      9800 non-null   datetime64[ns]
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   object
dtypes: datetime64[ns](2), float64(1), int64(1), object(14)
memory usage: 1.3+ MB

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368

In [48]:
# Conversion de sales en float

# df_sales["Sales"] = df_sales["Sales"].astype(float)
df_sales[df_sales["Sales"].astype(str).str.contains("GB", na=False)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
181,182,CA-2015-166191,2015-12-05,2015-12-09,Second Class,DK-13150,David Kendrick,Corporate,United States,Decatur,Illinois,62521.0,Central,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,16GB
430,431,US-2017-123750,2017-04-15,2017-04-21,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,North Carolina,28052.0,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,16GB
431,432,US-2017-123750,2017-04-15,2017-04-21,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,North Carolina,28052.0,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,16GB
1406,1407,US-2015-118486,2015-04-06,2015-04-08,First Class,SD-20485,Shirley Daniels,Home Office,United States,Philadelphia,Pennsylvania,19143.0,East,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,16GB
1969,1970,CA-2018-117485,2018-09-23,2018-09-29,Standard Class,BD-11320,Bill Donatelli,Consumer,United States,Tulsa,Oklahoma,74133.0,Central,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,16GB
1971,1972,CA-2018-140242,2018-05-06,2018-05-11,Standard Class,ML-17755,Max Ludwig,Home Office,United States,Chicago,Illinois,60623.0,Central,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,16GB